[build]
  command = "next build"
  publish = ".next"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[context.production.environment]
  [[redirects]]
    from = "https://shop.overcomewithchrist.com"
    to = "https://overcomewithchrist.com/shop"
    status = 301
    force = true
