[build]
  command = "npm run build && npm run export"
  functions = "out_functions"
  publish = "out"
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[context.production.environment]
  NODE_ENV = "production"
  NEXT_SERVERLESS = "true"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"