[build]
  command = "next build"
  publish = ".next"
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[context.production.environment]
  NODE_ENV = "production"
