backend: 
  name: git-gateway
#  name: test-repo
  branch: main
  publish_mode: editorial_workflow
media_library:
  name: cloudinary
  use_secure_url: true
  config:
    cloud_name: dn7ubiddg
    api_key: 866914922276626
display_url: '/'
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
media_folder: public/img
public_folder: img
collections:
  - name: "page"
    label: "Page"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "post"
    label: "Posts"
    label_singular: "Post"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Bible Study", "Resources", "Testimony", "Salvation", "Prayer", "Creative"]}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Video Link", name: "videoLink", widget: "string", required: false }
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "LL", format: "LL"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string", default: "Cyntia Seumo" }
